name: ecopayhood
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Fonts
  google_fonts: ^8.1.0

  # Backend
  supabase_flutter: ^2.0.0

  # UI
  pin_code_fields: ^8.0.1
  stop_watch_timer: ^3.1.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # Folder assets baru
    - lib/Assets/images/

    # Assets lama (hapus jika semuanya sudah dipindahkan ke lib/Assets/images/)
    - assets/Rectangle5.png
    - assets/Logo.png
    - assets/G.png
    - assets/K.png
    - assets/M.png
    - assets/O.png
    - assets/S.png
    - assets/H.png
    - assets/logoemail.png
    - assets/logogoogle.png
